#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /bin/busybox httpd -f -p 8081 -h /mnt/UDISK/fluidd
  procd_set_param respawn
  procd_close_instance
}
